Update CI-CD.yml

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -15,23 +15,38 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+
+    - name: Set up Python
+      uses: actions/setup-python@v4
       with:
         python-version: '3.x'
 
     - name: Install dependencies
       run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
 
     - name: Install Chrome
       run: |
         sudo apt-get update
         sudo apt-get install -y google-chrome-stable
 
+    - name: Fetch Chromedriver version
+      id: fetch_version
+      run: |
+        curl -s https://googlechromelabs.github.io/chrome-for-testing/ > page.html
+        VERSION=$(grep -oP '(?<=Chromedriver: )\d+\.\d+\.\d+' page.html)
+        echo "VERSION=${VERSION}" >> $GITHUB_ENV
+        echo "Version fetched: ${VERSION}"
+
     - name: Download and install ChromeDriver
       run: |
-        VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/ | grep -oP '(?<=Chromedriver: )\d+\.\d+\.\d+')
-        CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip"
+        if [ -z "${{ env.VERSION }}" ]; then
+          echo "Failed to fetch ChromeDriver version."
+          exit 1
+        fi
+        CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/${{ env.VERSION }}/chromedriver_linux64.zip"
+        echo "Downloading Chromedriver from: ${CHROMEDRIVER_URL}"
         wget $CHROMEDRIVER_URL
         unzip chromedriver_linux64.zip
         chmod +x chromedriver
@@ -39,7 +54,6 @@ jobs:
     - name: Run tests
       run: |
         robot -d ./logs -v BROWSER:chrome -v OPTIONS:"--headless --no-sandbox --disable-dev-shm-usage" tests/bdd_cases.robot
-
 
     - name: Upload Robot Framework reports
       uses: actions/upload-artifact@v2
